/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_koolew_mars_blur_ImageBlurTool */

#ifndef _Included_com_koolew_mars_blur_ImageBlurTool
#define _Included_com_koolew_mars_blur_ImageBlurTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_koolew_mars_blur_ImageBlurTool
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_koolew_mars_blur_ImageBlurTool_blurIntArray
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_koolew_mars_blur_ImageBlurTool
 * Method:    blurBitMap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_koolew_mars_blur_ImageBlurTool_blurBitMap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
