/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_koolew_mars_VideoShootActivity */

#ifndef _Included_com_koolew_mars_VideoShootActivity
#define _Included_com_koolew_mars_VideoShootActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_koolew_mars_VideoShootActivity_MEDIA_TYPE_IMAGE
#define com_koolew_mars_VideoShootActivity_MEDIA_TYPE_IMAGE 1L
#undef com_koolew_mars_VideoShootActivity_MEDIA_TYPE_VIDEO
#define com_koolew_mars_VideoShootActivity_MEDIA_TYPE_VIDEO 2L
/*
 * Class:     com_koolew_mars_VideoShootActivity
 * Method:    getAvcodecVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_koolew_mars_VideoShootActivity_getAvcodecVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
